version: "3"
##como se trata de um teste pode-se utilizar o usuario root nas configuracoes de banco ou criar um user especifico
services:
    db:
        image: mariadb
        container_name: db
        restart: always
        tty: true
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=root 
        networks:
          - desafio-network
    app:
        build: 
            context: ./
        container_name: app
        depends_on:
          - db
        tty: true
        command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && yarn start"
        networks:
          - desafio-network
        ports:
          - 3000:3001
networks:
    desafio-network:
        driver: bridge